# Configuration for Cloudflare Pages
name = "promptzy"

# The directory to deploy
pages_build_output_dir = "dist"

# Routes and other configurations
compatibility_date = "2023-10-30"

# Environment variables
[vars]
NODE_ENV = "production"

# Production-specific environment variables
[env.production.vars]
NODE_ENV = "production"

# Preview-specific environment variables
[env.preview.vars]
NODE_ENV = "production"
