# Configuration for Cloudflare Pages
name = "ai-prompt-dashboard"

# Build configuration
[build]
command = "npm run build"
output_directory = "dist"

# Environment variables
[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "production"
