// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxxaymvjwvzmmjekoxsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4eGF5bXZqd3Z6bW1qZWtveHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxOTY1NjksImV4cCI6MjA2Mjc3MjU2OX0.VyrQ5l6j5DPG6kn6FwpChXbn13lEbCEDrovbGTFkEkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);